[tool.black]
include = '\.pyi?$'
target-version = ['py36', 'py37']
exclude = '''
/(
    \.git
  | \.hg
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
line_length = 88
indent = '    '
skip = ['.tox', '.venv', 'build', 'dist']
known_standard_library = ['setuptools', 'pkg_resources']
known_test = 'pytest'
known_first_party = 'py21cmmc'
sections = ['FUTURE','STDLIB','COMPAT','TEST','THIRDPARTY','FIRSTPARTY','LOCALFOLDER']
default_section = 'THIRDPARTY'
profile = 'black'
