# Specify parameters that 21cmFAST uses. These are broken into flags, astro and cosmo parameters.
# Not all options are specified here.
user_params: {
    BOX_LEN: 150.0,
    HII_DIM: 50
}

cosmo_params: {
    RANDOM_SEED: 12345
}

astro_params: {
}

flag_options: {
  INHOMO_RECO: false,
}